variables:
- group: common

- name: buildContextFolder
  value: '.'

- name: imageRepository
  value: 'registry.see.asseco.com/docs/adaptive-ui-docs'

- name: dockerfilePath
  value: 'Dockerfile'

- name: moduleName
  value: 'adaptive-ui-cards'

pool: 'Digital'

resources:
  repositories:
    - repository: templates
      type: githubenterprise
      name: asseco-see/pipeline-templates
      ref: refs/heads/main
      endpoint: github

steps:
- script: |
    sed -i 's/root: \//root: \/adaptive-ui/g' source/nodejs/adaptivecards-site/_config.yml
  displayName: 'CHANGE_site_path_root'

- task: DockerAdvanced@0
  displayName: 'COMMIT_install'
  inputs:
    image: 'registry.see.asseco.com/tools/node:14-slim'
    secureFile: npm-asee-dp-robot
    dockerRegistryEndpoint: harbor
    commands: |
      cp npm-asee-dp-robot /root/.npmrc
      cp /source/source/samples/HostConfig/*.json /source/source/nodejs/adaptivecards-designer/src/hostConfigs/
      cd source/nodejs
      npm install --no-progress --loglevel=warn
      npx lerna bootstrap
      npx lerna run build

- task: DockerAdvanced@0
  displayName: 'COMMIT_release'
  inputs:
    image: 'registry.see.asseco.com/tools/node:14-slim'
    dockerRegistryEndpoint: harbor
    commands: |
      cd source/nodejs/adaptivecards-site
      npx lerna run release

- task: DockerAdvanced@0
  displayName: 'COMMIT_generate_version'
  inputs:
    image: 'registry.see.asseco.com/tools/image-tagger'
    dockerRegistryEndpoint: harbor
    envVars: |
      TAGGER_VERSION=v2
      GITHUB_TOKEN=$(githubToken)
      RELEASE=false

- script: |
    echo -e "\nCOPY --chown=1001:0 .version /" >> $(dockerfilePath)
  displayName: 'COMMIT_tag_version'
  
- task: DockerAdvanced@0
  displayName: 'COMMIT_NPM_publish_adaptivecards'
  inputs:
    image: 'registry.see.asseco.com/tools/angular-module-builder:11.0'
    dockerRegistryEndpoint: harbor
    secureFile: npm-asee-dp-robot
    commands: |
      cp npm-asee-dp-robot /root/.npmrc
      cd source/nodejs/adaptivecards
      npm run publish
      
- task: DockerAdvanced@0
  displayName: 'COMMIT_NPM_publish_adaptivecards_designer'
  inputs:
    image: 'registry.see.asseco.com/tools/angular-module-builder:11.0'
    dockerRegistryEndpoint: harbor
    secureFile: npm-asee-dp-robot
    commands: |
      cp npm-asee-dp-robot /root/.npmrc
      cd source/nodejs/adaptivecards-designer
      npm run publish

- task: DockerAdvanced@0
  displayName: 'COMMIT_publish'
  inputs:
    action: BuildAndPush
    context: $(buildContextFolder)
    image: $(imageRepository)
    dockerfile: $(dockerfilePath)
    dockerRegistryEndpoint: harbor

- script: |
    IFS=',' read -a tags <<< $(cat .tags)
    for tag in "${tags[@]}"
    do
      docker rmi $(imageRepository):${tag}
    done
  displayName: 'COMMIT_cleanup'
  condition: always()

- task: DockerAdvanced@0
  displayName: 'COMMIT_release_version'
  inputs:
    image: 'registry.see.asseco.com/tools/image-tagger'
    dockerRegistryEndpoint: harbor
    envVars: |
      TAGGER_VERSION=v2
      GITHUB_TOKEN=$(githubToken)
      NPM_ARTIFACTS=@asseco/adaptivecards:UI Kit;@asseco/adaptivecards-designer:UI Kit
      RELEASED_VERSION_API_URL=$(releasedVersionApiUrl)
      PUBLIC_DEVOPS_SERVER_URL=$(publicDevOpsServerUrl)
      PUBLIC_DEVOPS_PAT=$(publicDevOpsKey)

- script: |
    echo '##vso[task.setvariable variable=serviceName]$(moduleName)'
  displayName: 'COMMIT_override_serviceName'

- template: create-cd-artifacts.yml@templates
