###########################
### BASIC CONFIGURATION ###
###########################

### SCALING
replicaCount: 1

### SECURITY
masterPassword: ""

### CONTAINER REGISTRY
imageRegistryUsername: ""
imageRegistryPassword: ""

### INGRESS
ingressHost: ""

### SERVICE SPECIFIC VARIABLES
### END SERVICE SPECIFIC VARIABLES

##############################
### ADVANCED CONFIGURATION ###
##############################

### SECURITY
corsAllowedOrigins:
- "*"
containerSecurityContextRunAsUser: "1001"
podSecurityContextFSGroup: "1001"

### CONTAINER REGISTRY
imageRegistry: "registry.see.asseco.com"
imageRepository: "platform/adaptive-ui"
imageTag: "latest-dev"
imagePullExistingSecrets: []
imagePullPolicy: ""
genericImageRepository: "platform/generic"
genericImageTag: "3"

### INGRESS
ingressPaths:
- "/adaptive-ui"
ingressType: "nginx"
ingressClass: "nginx"
ingressAnnotations: {}
ingressTlsEnabled: true
ingressTlsOffloaded: false
ingressExistingTlsSecret: ""
ingressTlsServerCertificate: ""
ingressTlsServerKey: ""

### TRUSTED CERTIFICATES
trustedCA: ""
trustedCAExistingSecret: ""

### DEPENDENCIES
dependencies: []

### HARDWARE RESOURCES
memoryRequest: "128Mi"
memoryLimit: "256Mi"
cpuRequest: "50m"
# cpuLimit: 2
genericMemoryRequest: "16Mi"
genericMemoryLimit: "64Mi"
genericCpuRequest: "50m"
# genericCpuLimit: "200m"

### COMMUNICATION
environmentName: ""
clusterDomain: "cluster.local"
serviceType: "ClusterIP"
# serviceNodePort: 0

### SCHEDULING
podAntiAffinity: "soft"
nodeSelector: {}
tolerations: []

### ROLLOUT STRATEGY
deploymentStrategy: "RollingUpdate"
deploymentRollingUpdateMaxUnavailable: "25%"
deploymentRollingUpdateMaxSurge: "25%"

### CORE
extraSelectorLabels: {}
extraVariables: []
timezone: "UTC"
nameOverride: ""
fullnameOverride: ""
startupPath: "/app"
capabilitiesKubeVersion: ""

### SERVICE SPECIFIC VARIABLES
proxyIngressType: "nginx"
proxyIngressClass: "nginx"
proxyIngressAnnotations: {}
proxyIngressServiceName: "traefik"
proxyIngressServicePort: "websecure"
### END SERVICE SPECIFIC VARIABLES
