{{- if and .Values.ingressHost .Values.ingressPaths -}}
apiVersion: {{ include "asee.trait.ingress.api.version" . }}
kind: Ingress
metadata:
  name: {{ include "asee.trait.core.fullname" . }}-proxy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "asee.trait.core.metadata-labels" . | nindent 4 }}
  annotations:
    {{- include "asee.trait.ingress.annotations" ( dict "context" . "prefix" "proxy" ) | nindent 4 }}
spec:
  {{- if and .Values.proxyIngressClass ( include "asee.trait.ingress.supports.ingress-class-name" . ) }}
  ingressClassName: {{ .Values.proxyIngressClass }}
  {{- end }}
  rules:
  - host: {{ .Values.ingressHost }}
    http:
      paths:
      {{- range .Values.ingressPaths }}
      - path: {{ . }}
        {{- if ( include "asee.trait.ingress.supports.path-type" $ ) }}
        pathType: ImplementationSpecific
        {{- end }}
        backend: {{- include "asee.trait.ingress.backend" ( dict "context" $ "serviceName" ( tpl $.Values.proxyIngressServiceName $ ) "servicePort" $.Values.proxyIngressServicePort ) | nindent 10 }}
      {{- end }}
  {{- include "asee.trait.ingress.tls" . | nindent 2 }}
{{- end -}}
