{{- if and .Values.imageRegistryUsername .Values.imageRegistryPassword ( not .Values.imagePullExistingSecrets ) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "asee.trait.core.fullname" . }}-image-pull
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "asee.trait.core.metadata-labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\": {\"%s\": {\"auth\": \"%s\"}}}" .Values.imageRegistry ( printf "%s:%s" .Values.imageRegistryUsername .Values.imageRegistryPassword | b64enc ) | b64enc | quote }}
{{- end -}}