{{- if and .Values.trustedCA ( not .Values.trustedCAExistingSecret ) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "asee.trait.core.fullname" . }}-trusted-certificates
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "asee.trait.core.metadata-labels" . | nindent 4 }}
data:
  custom-ca-certificates.crt: {{ .Values.trustedCA }}
{{- end -}}