{{- if and .Values.enabled ( eq "true" ( include "helper.ingressEnabled" . ) ) -}}
apiVersion: {{ include "helper.ingressApiVersion" . }}
kind: Ingress
metadata:
  name: {{ include "helper.fullname" . | quote }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helper.metadataLabels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: {{ include "helper.ingressClass" . | quote }}
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
  {{- if .Values.global.ingress.sslOffloading }}
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  {{- end }}
    nginx.ingress.kubernetes.io/app-root: "/platform/"
    {{- include "helper.ingressAnnotations" . | nindent 4 }}
spec:
{{- if eq "true" ( include "helper.ingressTlsEnabled" . ) }}
  tls:
    - hosts:
        - {{ include "helper.ingressHost" . | quote }}
      secretName: {{ include "helper.ingressTlsSecretName" . | quote }}
{{- end }}
  rules:
  - host: {{ include "helper.ingressHost" . | quote }}
    http:
      paths:
        - backend:
            serviceName: {{ include "helper.fullname" . | quote }}
            servicePort: "http"
          path: {{ .Values.env.basePath | quote }}
        {{- with .Values.ingress.extraPaths }}
        {{- tpl . $ | nindent 8 }}
        {{- end }}
{{- end -}}
