//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.11.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from AdaptiveCardsTemplateParser.g4 by ANTLR 4.11.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="AdaptiveCardsTemplateParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.11.1")]
[System.CLSCompliant(false)]
public interface IAdaptiveCardsTemplateParserListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="AdaptiveCardsTemplateParser.json"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterJson([NotNull] AdaptiveCardsTemplateParser.JsonContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AdaptiveCardsTemplateParser.json"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitJson([NotNull] AdaptiveCardsTemplateParser.JsonContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AdaptiveCardsTemplateParser.obj"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterObj([NotNull] AdaptiveCardsTemplateParser.ObjContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AdaptiveCardsTemplateParser.obj"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitObj([NotNull] AdaptiveCardsTemplateParser.ObjContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>jsonPair</c>
	/// labeled alternative in <see cref="AdaptiveCardsTemplateParser.pair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterJsonPair([NotNull] AdaptiveCardsTemplateParser.JsonPairContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>jsonPair</c>
	/// labeled alternative in <see cref="AdaptiveCardsTemplateParser.pair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitJsonPair([NotNull] AdaptiveCardsTemplateParser.JsonPairContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>templateRootData</c>
	/// labeled alternative in <see cref="AdaptiveCardsTemplateParser.pair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTemplateRootData([NotNull] AdaptiveCardsTemplateParser.TemplateRootDataContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>templateRootData</c>
	/// labeled alternative in <see cref="AdaptiveCardsTemplateParser.pair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTemplateRootData([NotNull] AdaptiveCardsTemplateParser.TemplateRootDataContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>templateData</c>
	/// labeled alternative in <see cref="AdaptiveCardsTemplateParser.pair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTemplateData([NotNull] AdaptiveCardsTemplateParser.TemplateDataContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>templateData</c>
	/// labeled alternative in <see cref="AdaptiveCardsTemplateParser.pair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTemplateData([NotNull] AdaptiveCardsTemplateParser.TemplateDataContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>templateWhen</c>
	/// labeled alternative in <see cref="AdaptiveCardsTemplateParser.pair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTemplateWhen([NotNull] AdaptiveCardsTemplateParser.TemplateWhenContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>templateWhen</c>
	/// labeled alternative in <see cref="AdaptiveCardsTemplateParser.pair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTemplateWhen([NotNull] AdaptiveCardsTemplateParser.TemplateWhenContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AdaptiveCardsTemplateParser.array"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArray([NotNull] AdaptiveCardsTemplateParser.ArrayContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AdaptiveCardsTemplateParser.array"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArray([NotNull] AdaptiveCardsTemplateParser.ArrayContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>valueTemplateString</c>
	/// labeled alternative in <see cref="AdaptiveCardsTemplateParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValueTemplateString([NotNull] AdaptiveCardsTemplateParser.ValueTemplateStringContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>valueTemplateString</c>
	/// labeled alternative in <see cref="AdaptiveCardsTemplateParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValueTemplateString([NotNull] AdaptiveCardsTemplateParser.ValueTemplateStringContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>valueTemplateStringWithRoot</c>
	/// labeled alternative in <see cref="AdaptiveCardsTemplateParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValueTemplateStringWithRoot([NotNull] AdaptiveCardsTemplateParser.ValueTemplateStringWithRootContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>valueTemplateStringWithRoot</c>
	/// labeled alternative in <see cref="AdaptiveCardsTemplateParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValueTemplateStringWithRoot([NotNull] AdaptiveCardsTemplateParser.ValueTemplateStringWithRootContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>valueString</c>
	/// labeled alternative in <see cref="AdaptiveCardsTemplateParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValueString([NotNull] AdaptiveCardsTemplateParser.ValueStringContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>valueString</c>
	/// labeled alternative in <see cref="AdaptiveCardsTemplateParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValueString([NotNull] AdaptiveCardsTemplateParser.ValueStringContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>valueNumber</c>
	/// labeled alternative in <see cref="AdaptiveCardsTemplateParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValueNumber([NotNull] AdaptiveCardsTemplateParser.ValueNumberContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>valueNumber</c>
	/// labeled alternative in <see cref="AdaptiveCardsTemplateParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValueNumber([NotNull] AdaptiveCardsTemplateParser.ValueNumberContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>valueObject</c>
	/// labeled alternative in <see cref="AdaptiveCardsTemplateParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValueObject([NotNull] AdaptiveCardsTemplateParser.ValueObjectContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>valueObject</c>
	/// labeled alternative in <see cref="AdaptiveCardsTemplateParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValueObject([NotNull] AdaptiveCardsTemplateParser.ValueObjectContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>valueArray</c>
	/// labeled alternative in <see cref="AdaptiveCardsTemplateParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValueArray([NotNull] AdaptiveCardsTemplateParser.ValueArrayContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>valueArray</c>
	/// labeled alternative in <see cref="AdaptiveCardsTemplateParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValueArray([NotNull] AdaptiveCardsTemplateParser.ValueArrayContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>valueTrue</c>
	/// labeled alternative in <see cref="AdaptiveCardsTemplateParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValueTrue([NotNull] AdaptiveCardsTemplateParser.ValueTrueContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>valueTrue</c>
	/// labeled alternative in <see cref="AdaptiveCardsTemplateParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValueTrue([NotNull] AdaptiveCardsTemplateParser.ValueTrueContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>valueFalse</c>
	/// labeled alternative in <see cref="AdaptiveCardsTemplateParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValueFalse([NotNull] AdaptiveCardsTemplateParser.ValueFalseContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>valueFalse</c>
	/// labeled alternative in <see cref="AdaptiveCardsTemplateParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValueFalse([NotNull] AdaptiveCardsTemplateParser.ValueFalseContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>valueNull</c>
	/// labeled alternative in <see cref="AdaptiveCardsTemplateParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValueNull([NotNull] AdaptiveCardsTemplateParser.ValueNullContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>valueNull</c>
	/// labeled alternative in <see cref="AdaptiveCardsTemplateParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValueNull([NotNull] AdaptiveCardsTemplateParser.ValueNullContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>templatedString</c>
	/// labeled alternative in <see cref="AdaptiveCardsTemplateParser.templateString"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTemplatedString([NotNull] AdaptiveCardsTemplateParser.TemplatedStringContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>templatedString</c>
	/// labeled alternative in <see cref="AdaptiveCardsTemplateParser.templateString"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTemplatedString([NotNull] AdaptiveCardsTemplateParser.TemplatedStringContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>templateStringWithRoot</c>
	/// labeled alternative in <see cref="AdaptiveCardsTemplateParser.templateRoot"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTemplateStringWithRoot([NotNull] AdaptiveCardsTemplateParser.TemplateStringWithRootContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>templateStringWithRoot</c>
	/// labeled alternative in <see cref="AdaptiveCardsTemplateParser.templateRoot"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTemplateStringWithRoot([NotNull] AdaptiveCardsTemplateParser.TemplateStringWithRootContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>valueTemplateExpression</c>
	/// labeled alternative in <see cref="AdaptiveCardsTemplateParser.templateExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValueTemplateExpression([NotNull] AdaptiveCardsTemplateParser.ValueTemplateExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>valueTemplateExpression</c>
	/// labeled alternative in <see cref="AdaptiveCardsTemplateParser.templateExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValueTemplateExpression([NotNull] AdaptiveCardsTemplateParser.ValueTemplateExpressionContext context);
}
