//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.11.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from AdaptiveCardsTemplateParser.g4 by ANTLR 4.11.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IAdaptiveCardsTemplateParserListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.11.1")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class AdaptiveCardsTemplateParserBaseListener : IAdaptiveCardsTemplateParserListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="AdaptiveCardsTemplateParser.json"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterJson([NotNull] AdaptiveCardsTemplateParser.JsonContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AdaptiveCardsTemplateParser.json"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitJson([NotNull] AdaptiveCardsTemplateParser.JsonContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AdaptiveCardsTemplateParser.obj"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterObj([NotNull] AdaptiveCardsTemplateParser.ObjContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AdaptiveCardsTemplateParser.obj"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitObj([NotNull] AdaptiveCardsTemplateParser.ObjContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>jsonPair</c>
	/// labeled alternative in <see cref="AdaptiveCardsTemplateParser.pair"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterJsonPair([NotNull] AdaptiveCardsTemplateParser.JsonPairContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>jsonPair</c>
	/// labeled alternative in <see cref="AdaptiveCardsTemplateParser.pair"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitJsonPair([NotNull] AdaptiveCardsTemplateParser.JsonPairContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>templateRootData</c>
	/// labeled alternative in <see cref="AdaptiveCardsTemplateParser.pair"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTemplateRootData([NotNull] AdaptiveCardsTemplateParser.TemplateRootDataContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>templateRootData</c>
	/// labeled alternative in <see cref="AdaptiveCardsTemplateParser.pair"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTemplateRootData([NotNull] AdaptiveCardsTemplateParser.TemplateRootDataContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>templateData</c>
	/// labeled alternative in <see cref="AdaptiveCardsTemplateParser.pair"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTemplateData([NotNull] AdaptiveCardsTemplateParser.TemplateDataContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>templateData</c>
	/// labeled alternative in <see cref="AdaptiveCardsTemplateParser.pair"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTemplateData([NotNull] AdaptiveCardsTemplateParser.TemplateDataContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>templateWhen</c>
	/// labeled alternative in <see cref="AdaptiveCardsTemplateParser.pair"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTemplateWhen([NotNull] AdaptiveCardsTemplateParser.TemplateWhenContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>templateWhen</c>
	/// labeled alternative in <see cref="AdaptiveCardsTemplateParser.pair"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTemplateWhen([NotNull] AdaptiveCardsTemplateParser.TemplateWhenContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AdaptiveCardsTemplateParser.array"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArray([NotNull] AdaptiveCardsTemplateParser.ArrayContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AdaptiveCardsTemplateParser.array"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArray([NotNull] AdaptiveCardsTemplateParser.ArrayContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>valueTemplateString</c>
	/// labeled alternative in <see cref="AdaptiveCardsTemplateParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValueTemplateString([NotNull] AdaptiveCardsTemplateParser.ValueTemplateStringContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>valueTemplateString</c>
	/// labeled alternative in <see cref="AdaptiveCardsTemplateParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValueTemplateString([NotNull] AdaptiveCardsTemplateParser.ValueTemplateStringContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>valueTemplateStringWithRoot</c>
	/// labeled alternative in <see cref="AdaptiveCardsTemplateParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValueTemplateStringWithRoot([NotNull] AdaptiveCardsTemplateParser.ValueTemplateStringWithRootContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>valueTemplateStringWithRoot</c>
	/// labeled alternative in <see cref="AdaptiveCardsTemplateParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValueTemplateStringWithRoot([NotNull] AdaptiveCardsTemplateParser.ValueTemplateStringWithRootContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>valueString</c>
	/// labeled alternative in <see cref="AdaptiveCardsTemplateParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValueString([NotNull] AdaptiveCardsTemplateParser.ValueStringContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>valueString</c>
	/// labeled alternative in <see cref="AdaptiveCardsTemplateParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValueString([NotNull] AdaptiveCardsTemplateParser.ValueStringContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>valueNumber</c>
	/// labeled alternative in <see cref="AdaptiveCardsTemplateParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValueNumber([NotNull] AdaptiveCardsTemplateParser.ValueNumberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>valueNumber</c>
	/// labeled alternative in <see cref="AdaptiveCardsTemplateParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValueNumber([NotNull] AdaptiveCardsTemplateParser.ValueNumberContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>valueObject</c>
	/// labeled alternative in <see cref="AdaptiveCardsTemplateParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValueObject([NotNull] AdaptiveCardsTemplateParser.ValueObjectContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>valueObject</c>
	/// labeled alternative in <see cref="AdaptiveCardsTemplateParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValueObject([NotNull] AdaptiveCardsTemplateParser.ValueObjectContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>valueArray</c>
	/// labeled alternative in <see cref="AdaptiveCardsTemplateParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValueArray([NotNull] AdaptiveCardsTemplateParser.ValueArrayContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>valueArray</c>
	/// labeled alternative in <see cref="AdaptiveCardsTemplateParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValueArray([NotNull] AdaptiveCardsTemplateParser.ValueArrayContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>valueTrue</c>
	/// labeled alternative in <see cref="AdaptiveCardsTemplateParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValueTrue([NotNull] AdaptiveCardsTemplateParser.ValueTrueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>valueTrue</c>
	/// labeled alternative in <see cref="AdaptiveCardsTemplateParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValueTrue([NotNull] AdaptiveCardsTemplateParser.ValueTrueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>valueFalse</c>
	/// labeled alternative in <see cref="AdaptiveCardsTemplateParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValueFalse([NotNull] AdaptiveCardsTemplateParser.ValueFalseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>valueFalse</c>
	/// labeled alternative in <see cref="AdaptiveCardsTemplateParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValueFalse([NotNull] AdaptiveCardsTemplateParser.ValueFalseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>valueNull</c>
	/// labeled alternative in <see cref="AdaptiveCardsTemplateParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValueNull([NotNull] AdaptiveCardsTemplateParser.ValueNullContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>valueNull</c>
	/// labeled alternative in <see cref="AdaptiveCardsTemplateParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValueNull([NotNull] AdaptiveCardsTemplateParser.ValueNullContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>templatedString</c>
	/// labeled alternative in <see cref="AdaptiveCardsTemplateParser.templateString"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTemplatedString([NotNull] AdaptiveCardsTemplateParser.TemplatedStringContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>templatedString</c>
	/// labeled alternative in <see cref="AdaptiveCardsTemplateParser.templateString"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTemplatedString([NotNull] AdaptiveCardsTemplateParser.TemplatedStringContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>templateStringWithRoot</c>
	/// labeled alternative in <see cref="AdaptiveCardsTemplateParser.templateRoot"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTemplateStringWithRoot([NotNull] AdaptiveCardsTemplateParser.TemplateStringWithRootContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>templateStringWithRoot</c>
	/// labeled alternative in <see cref="AdaptiveCardsTemplateParser.templateRoot"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTemplateStringWithRoot([NotNull] AdaptiveCardsTemplateParser.TemplateStringWithRootContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>valueTemplateExpression</c>
	/// labeled alternative in <see cref="AdaptiveCardsTemplateParser.templateExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValueTemplateExpression([NotNull] AdaptiveCardsTemplateParser.ValueTemplateExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>valueTemplateExpression</c>
	/// labeled alternative in <see cref="AdaptiveCardsTemplateParser.templateExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValueTemplateExpression([NotNull] AdaptiveCardsTemplateParser.ValueTemplateExpressionContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
