apiVersion: v1
kind: Service
metadata:
  name: {{ include "asee.trait.core.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "asee.trait.core.metadata-labels" . | nindent 4 }}
spec:
  type: {{ include "asee.trait.communication.service.type" . }}
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
    {{- if ( eq ( include "asee.trait.communication.service.type" . ) "ClusterIP" ) }}
    nodePort: null
    {{- else if and ( eq ( include "asee.trait.communication.service.type" . ) "NodePort" ) .Values.serviceNodePort }}
    nodePort: {{ .Values.serviceNodePort }}
    {{- end }}
  {{- include "asee.adaptive-ui.513iuibv.extension.service.ports" . | nindent 2 }}
  selector:
    {{- include "asee.trait.core.selector-labels" . | nindent 4 }}
    {{- include "asee.trait.core.extra-selector-labels" . | nindent 4 }}